### ISSUE TITLE
GetDocumentById in OwnCollection states POST, but the link is only a GET

### ISSUE THREAD

**Issue by grmpfhmbl** [ZGIS/smart-portal-webgui#41]
When we offer a link to click on, the link should provide the correct result. So either we POST the Request-Data from the DB, before opening the new TAB, or we delete the link. I'd opt for variant 1 :-)

**Comment by allixender** [comment]
@grmpfhmbl That would be here

https://github.com/ZGIS/smart-portal-backend/blob/master/app/services/OwcCollectionsService.scala#L149-L154

It is a fully configured POST request, so the provided HREF in the WebGUI is not appropriate, I agree. But some requests won't be configurable nicely in a GET form, thus, we need to come up with an idea. Furtermore, most users won't be able to make use of the XML response of such OGC requests anyway. Stil, in the context document they need to stay, because they need to be available for subsequent machine/service functionality.

Just deleting POST requests in general is not a good idea, but: In this case the GetRecordById request could also be expressed as GET request URL + query string.

It's another thing, how those links are presented in OwnCollection though
